# users.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Userfile
#
# Auto-generated by install script
# Date: Fri, 23 Feb 2024 22:51:58 +0000
#
# Format:
# login:passwordhash:Real Name:email:groups,comma,separated

ryoung:$2y$10$oSKshr75pRsGZskj5PfSmOgLjGtODuRgskqZ0hzIhHpkaxYNxil.K:Ryan Young:ryan.jsyoung@protonmail.com:admin,user
